# Generated by Django 4.2.1 on 2023-05-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_resumesection_next_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePersonal',
            fields=[
                ('resumesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.resumesection')),
                ('title', models.CharField(max_length=32)),
                ('linked_in', models.CharField(max_length=32)),
                ('github', models.CharField(max_length=32)),
                ('pitch', models.TextField()),
            ],
            bases=('api.resumesection',),
        ),
        migrations.CreateModel(
            name='ResumeSkills',
            fields=[
                ('resumesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.resumesection')),
                ('skills', models.JSONField()),
            ],
            bases=('api.resumesection',),
        ),
        migrations.RemoveField(
            model_name='resumesection',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sectionformat',
            name='type',
        ),
    ]
