# Generated by Django 4.2.1 on 2023-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resumepersonal_resumeskills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumesection',
            name='next_section',
        ),
        migrations.RemoveField(
            model_name='resumesection',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='resumesection',
            name='section_format',
        ),
        migrations.RemoveField(
            model_name='resumeskills',
            name='resumesection_ptr',
        ),
        migrations.RemoveField(
            model_name='sectionformat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start',
        ),
        migrations.AddField(
            model_name='resume',
            name='data',
            field=models.JSONField(default={'test': 'test'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='format',
            field=models.JSONField(default={'test': 'test'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResumePersonal',
        ),
        migrations.DeleteModel(
            name='ResumeSection',
        ),
        migrations.DeleteModel(
            name='ResumeSkills',
        ),
        migrations.DeleteModel(
            name='SectionFormat',
        ),
    ]
