# Generated by Django 4.2.1 on 2023-05-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_resumesection_next_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='owner',
        ),
    ]
